### ISSUE TITLE
Adding support for domination slots

### ISSUE THREAD

**Issue by Tsiou** [stroeckx/LegendaryStockTracker#5]
I'm trying to add a setting that would skip restocking legendaries on slots with domination sockets.

I figured out that the way to do this would be by adding a check in the **LST:UpdateRestockList** function that would skip the restock if it belongs in a domination slot and restocking domination slots is disabled in the settings.

Would I be correct in adding the domination slot data in the **core.lua** file, in the **LegendaryItemData** array, with a name of _"dominationSlot" = bool_ field?

If I actually added the feature, would you be interested in a pull request with the changes?

Thank you for the extremely helpful addon.

**Comment by stroeckx** [comment]
Thanks for the addition, updated the table view to match this change and added this feature!
