### ISSUE TITLE
Attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by soeron** [stroeckx/LegendaryStockTracker#7]
With the latest version v2.19.5, this error started to pop when i press the update button on the restock tab.
 I have a bank character which doesnt have any profession and is lvl 13 so he cant have vestige at all. The error comes from line 2013, where you return a string "Not scanned" in GetCraftCostWithVestige function and try to do arimetics with it. Commenting the line fixes the error.

**Comment by stroeckx** [comment]
Could you send me the full error?
Preferably on discord, linked in the LST curseforge page

**Comment by stroeckx** [comment]
Should be fixed in the next update!
